patch: add missing import traceback in scheduler
upstream: https://github.com/CumulusNetworks/ifupdown2/pull/267

if a script in /etc/network/ifup.d/ is segfaulting,

ifup is crashing with

info: executing2 /etc/network/if-up.d/postfix
debug: lo: up : running script /etc/network/if-up.d/resolved info: executing2 /etc/network/if-up.d/resolved
error: name 'traceback' is not defined
debug: saving state ..
info: exit status 1
Signed-off-by: Alexandre Derumier <aderumier@odiso.com>
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>